### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by barwinco** [t9md/vim-ezbar#6]
There are broken links in readme:

Mode aware [Mode](https://camo.githubusercontent.com/b8b58b76ae9545c6c510d30b572763785ccaaf03/68747470733a2f2f7261772e6769746875622e636f6d2f74396d642f74396d642f6d61737465722f696d672f657a6261722f6d6f64655f696e736572742e706e67)
Change color when filename is XXX in this case begin with tryit [Filename](https://camo.githubusercontent.com/9206c074ee46a8bc3bce9adedca81c4d0a71e30b/68747470733a2f2f7261772e6769746875622e636f6d2f74396d642f74396d642f6d61737465722f696d672f657a6261722f66696c656e616d655f6e6f746966792e706e67)
Change color when git branch is not master [Git-1](https://camo.githubusercontent.com/ad51f3fc2e63802be07517ab64a949c0ae0e766c/68747470733a2f2f7261772e6769746875622e636f6d2f74396d642f74396d642f6d61737465722f696d672f657a6261722f6769742d6272616e63685f6e6f746966792e706e67)
```
Not Found
```

**Comment by t9md** [comment]
thanks, fixed it.
